<#
.SYNOPSIS
    Deploys Sigma-converted saved searches to Splunk via REST API.

.DESCRIPTION
    This script reads savedsearches.conf generated by convert-to-splunk.py
    and deploys each saved search to Splunk using the REST API.
    Supports creating new searches and updating existing ones.

.PARAMETER SplunkHost
    Splunk server hostname or IP address

.PARAMETER SplunkPort
    Splunk management port (default: 8089)

.PARAMETER Username
    Splunk admin username

.PARAMETER Password
    Splunk admin password (will prompt if not provided)

.PARAMETER App
    Splunk app context for the saved searches (default: search)

.PARAMETER InputFile
    Path to savedsearches.conf file (default: splunk_output/savedsearches.conf)

.PARAMETER DryRun
    Parse and validate without deploying to Splunk

.EXAMPLE
    .\deploy-to-splunk.ps1 -SplunkHost splunk.company.com -Username admin
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$SplunkHost,

    [int]$SplunkPort = 8089,

    [Parameter(Mandatory=$true)]
    [string]$Username,

    [SecureString]$Password,

    [string]$App = "search",

    [string]$InputFile = "splunk_output/savedsearches.conf",

    [switch]$DryRun,

    [switch]$EnableAlerts,

    [string]$AlertAction = "email",

    [string]$AlertEmail
)

# Ignore SSL certificate errors (for self-signed certs in lab environments)
if (-not ([System.Management.Automation.PSTypeName]'ServerCertificateValidationCallback').Type) {
    Add-Type @"
    using System;
    using System.Net;
    using System.Net.Security;
    using System.Security.Cryptography.X509Certificates;
    public class ServerCertificateValidationCallback {
        public static void Ignore() {
            ServicePointManager.ServerCertificateValidationCallback =
                delegate(Object obj, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors) { return true; };
        }
    }
"@
}
[ServerCertificateValidationCallback]::Ignore()
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

function Parse-SavedSearchesConf {
    param([string]$FilePath)

    $searches = @()
    $currentSearch = $null
    $currentKey = $null
    $continuingValue = $false

    $content = Get-Content -Path $FilePath -Encoding UTF8

    foreach ($line in $content) {
        # Handle line continuation
        if ($continuingValue -and $currentSearch -and $currentKey) {
            $trimmedLine = $line.Trim()
            if ($trimmedLine.EndsWith('\')) {
                # More continuation - append without the backslash
                $currentSearch.Properties[$currentKey] += $trimmedLine.TrimEnd('\')
            } else {
                # End of continuation
                $currentSearch.Properties[$currentKey] += $trimmedLine
                $continuingValue = $false
                $currentKey = $null
            }
            continue
        }

        $line = $line.Trim()

        # Skip empty lines and comments
        if ([string]::IsNullOrEmpty($line) -or $line.StartsWith('#')) {
            continue
        }

        # New stanza (search name)
        if ($line -match '^\[(.+)\]$') {
            if ($currentSearch -and $currentSearch.Name -ne 'default') {
                $searches += $currentSearch
            }
            $currentSearch = @{
                Name = $Matches[1]
                Properties = @{}
            }
            $continuingValue = $false
            $currentKey = $null
        }
        # Property
        elseif ($line -match '^(\w[\w\.]+)\s*=\s*(.*)$' -and $currentSearch) {
            $key = $Matches[1]
            $value = $Matches[2]

            if ($value.EndsWith('\')) {
                # Line continues on next line
                $currentSearch.Properties[$key] = $value.TrimEnd('\')
                $currentKey = $key
                $continuingValue = $true
            } else {
                $currentSearch.Properties[$key] = $value
            }
        }
    }

    # Add the last search
    if ($currentSearch -and $currentSearch.Name -ne 'default') {
        $searches += $currentSearch
    }

    return $searches
}

function Get-SplunkAuthToken {
    param(
        [string]$Server,
        [int]$Port,
        [string]$Username,
        [SecureString]$Password
    )

    $cred = New-Object System.Management.Automation.PSCredential($Username, $Password)
    $plainPassword = $cred.GetNetworkCredential().Password

    $uri = "https://${Server}:${Port}/services/auth/login?output_mode=json"
    $body = @{
        username = $Username
        password = $plainPassword
    }

    try {
        $response = Invoke-RestMethod -Uri $uri -Method Post -Body $body -ErrorAction Stop
        $sessionKey = $response.sessionKey
        if (-not $sessionKey) {
            throw "No session key in response"
        }
        return $sessionKey.Trim()
    }
    catch {
        throw "Failed to authenticate with Splunk: $_"
    }
}

function Test-SavedSearchExists {
    param(
        [string]$Server,
        [int]$Port,
        [string]$SessionKey,
        [string]$App,
        [string]$SearchName
    )

    $encodedName = [uri]::EscapeDataString($SearchName)
    $uri = "https://${Server}:${Port}/servicesNS/nobody/${App}/saved/searches/${encodedName}?output_mode=json"

    $headers = @{
        Authorization = "Splunk $SessionKey"
    }

    try {
        $null = Invoke-RestMethod -Uri $uri -Method Get -Headers $headers -ErrorAction Stop
        return $true
    }
    catch {
        $statusCode = 0
        if ($_.Exception.Response) {
            $statusCode = [int]$_.Exception.Response.StatusCode
        }
        if ($statusCode -eq 404) {
            return $false
        }
        # For auth errors (401/403), throw to surface the issue
        if ($statusCode -eq 401 -or $statusCode -eq 403) {
            throw "Authorization failed checking search existence: $($_.Exception.Message)"
        }
        return $false
    }
}

function Deploy-SavedSearch {
    param(
        [string]$Server,
        [int]$Port,
        [string]$SessionKey,
        [string]$App,
        [hashtable]$Search,
        [bool]$EnableAlert,
        [string]$AlertAction,
        [string]$AlertEmail
    )

    $searchName = $Search.Name
    $exists = Test-SavedSearchExists -Server $Server -Port $Port -SessionKey $SessionKey -App $App -SearchName $searchName

    $headers = @{
        Authorization = "Splunk $SessionKey"
        "Content-Type" = "application/x-www-form-urlencoded"
    }

    # Build the body parameters
    $body = @{
        name = $searchName
        search = $Search.Properties['search']
    }

    # Add description if present
    if ($Search.Properties['description']) {
        $body['description'] = $Search.Properties['description']
    }

    # Add time range
    if ($Search.Properties['dispatch.earliest_time']) {
        $body['dispatch.earliest_time'] = $Search.Properties['dispatch.earliest_time']
    }
    if ($Search.Properties['dispatch.latest_time']) {
        $body['dispatch.latest_time'] = $Search.Properties['dispatch.latest_time']
    }

    # Configure as alert if requested
    if ($EnableAlert) {
        $body['is_scheduled'] = 1
        $body['cron_schedule'] = '*/15 * * * *'  # Every 15 minutes
        $body['alert.track'] = 1
        $body['alert.severity'] = 4  # High
        $body['alert_type'] = 'number of events'
        $body['alert_comparator'] = 'greater than'
        $body['alert_threshold'] = 0
        $body['actions'] = $AlertAction

        if ($AlertAction -eq 'email' -and $AlertEmail) {
            $body['action.email.to'] = $AlertEmail
            $body['action.email.subject'] = "Sigma Alert: $searchName"
        }
    }

    if ($exists) {
        # Update existing search
        $encodedName = [uri]::EscapeDataString($searchName)
        $uri = "https://${Server}:${Port}/servicesNS/nobody/${App}/saved/searches/${encodedName}?output_mode=json"
        $body.Remove('name')  # Can't update name

        try {
            $null = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ErrorAction Stop
            return @{ Status = 'Updated'; Name = $searchName }
        }
        catch {
            return @{ Status = 'Failed'; Name = $searchName; Error = $_.Exception.Message }
        }
    }
    else {
        # Create new search
        $uri = "https://${Server}:${Port}/servicesNS/nobody/${App}/saved/searches?output_mode=json"

        try {
            $null = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ErrorAction Stop
            return @{ Status = 'Created'; Name = $searchName }
        }
        catch {
            return @{ Status = 'Failed'; Name = $searchName; Error = $_.Exception.Message }
        }
    }
}

# Main execution
Write-Host "=" * 60
Write-Host "Splunk Saved Search Deployment"
Write-Host "=" * 60
Write-Host ""

# Check input file exists
if (-not (Test-Path $InputFile)) {
    Write-Error "Input file not found: $InputFile"
    Write-Host "Run convert-to-splunk.py first to generate savedsearches.conf"
    exit 1
}

# Parse the savedsearches.conf
Write-Host "Parsing $InputFile..."
$searches = Parse-SavedSearchesConf -FilePath $InputFile
Write-Host "Found $($searches.Count) saved searches"
Write-Host ""

if ($DryRun) {
    Write-Host "[DRY RUN] Would deploy the following searches:"
    foreach ($search in $searches) {
        Write-Host "  - $($search.Name)"
        if ($search.Properties['search']) {
            $truncated = $search.Properties['search'].Substring(0, [Math]::Min(60, $search.Properties['search'].Length))
            Write-Host "    Search: $truncated..."
        }
    }
    Write-Host ""
    Write-Host "Run without -DryRun to deploy to Splunk"
    exit 0
}

# Get password if not provided
if (-not $Password) {
    $Password = Read-Host -Prompt "Enter Splunk password for $Username" -AsSecureString
}

# Authenticate
Write-Host "Authenticating with Splunk at ${SplunkHost}:${SplunkPort}..."
try {
    $sessionKey = Get-SplunkAuthToken -Server $SplunkHost -Port $SplunkPort -Username $Username -Password $Password
    Write-Host "Authentication successful (token length: $($sessionKey.Length))"
}
catch {
    Write-Error "Authentication failed: $_"
    exit 1
}

Write-Host ""
Write-Host "Deploying saved searches to app: $App"
Write-Host "-" * 40

$results = @{
    Created = @()
    Updated = @()
    Failed = @()
}

foreach ($search in $searches) {
    Write-Host "Deploying: $($search.Name)..." -NoNewline

    $result = Deploy-SavedSearch `
        -Server $SplunkHost `
        -Port $SplunkPort `
        -SessionKey $sessionKey `
        -App $App `
        -Search $search `
        -EnableAlert:$EnableAlerts `
        -AlertAction $AlertAction `
        -AlertEmail $AlertEmail

    switch ($result.Status) {
        'Created' {
            Write-Host " CREATED" -ForegroundColor Green
            $results.Created += $result.Name
        }
        'Updated' {
            Write-Host " UPDATED" -ForegroundColor Yellow
            $results.Updated += $result.Name
        }
        'Failed' {
            Write-Host " FAILED: $($result.Error)" -ForegroundColor Red
            $results.Failed += $result
        }
    }
}

Write-Host ""
Write-Host "=" * 60
Write-Host "Deployment Summary"
Write-Host "=" * 60
Write-Host "Created: $($results.Created.Count)" -ForegroundColor Green
Write-Host "Updated: $($results.Updated.Count)" -ForegroundColor Yellow
Write-Host "Failed:  $($results.Failed.Count)" -ForegroundColor Red

if ($results.Failed.Count -gt 0) {
    Write-Host ""
    Write-Host "Failed deployments:"
    foreach ($fail in $results.Failed) {
        Write-Host "  - $($fail.Name): $($fail.Error)" -ForegroundColor Red
    }
    exit 1
}

Write-Host ""
Write-Host "Deployment complete! Searches are available in Splunk under:"
Write-Host "  Settings -> Searches, reports, and alerts"
exit 0
